### ISSUE TITLE
backend documentation

### ISSUE THREAD

**Issue by throberto** [aluisribeiro/petsaojoao-backend#12]
Precisamos documentar as rotas dos recursos do nosso backend.
Sugiro duas ferramentas open source, sendo [apiDoc](https://apidocjs.com/) ou [Swagger](https://swagger.io/).

Ambas oferecem suporte a plataforma node e são simples de implementar.

@aluisribeiro o que acha?

**Comment by aluisribeiro** [comment]
Eu acho bacana @thiagon4code.
