### ISSUE TITLE
Lista de Espécies, Raças e Cores -- Seeders

### ISSUE THREAD

**Issue by thiagon4code** [aluisribeiro/petsaojoao-backend#9]
Olá pessoal. Estou criando algumas seeders iniciais do projeto para que algumas tabelas de cadastro único já possam ser populadas (facilita o desenvolvimento pois não há necessidade de adicionar registros a todo momento).

Temos as tabelas "Espécie" e "Raças".
Raça é associada a Espécie.

Em um primeiro momento imagino que as únicas duas espécies que teremos seria "Cachorro(a)" e "Gato(a)". Seria interessante adicionar um terceiro registro chamado "Outro(a)" ? O que acham?

Em relação as raças, vou adicionar cinco de cada espécie inicialmente, porém devemos pensar como essa tabela será populada tendo em mente que existem milhares de raças, seria interessante também adicionar o "Outro(a)" ou "Não Reconheço"...

Sobre as cores, imagino que não tenha necessidade de adicionar todas paletas possíveis (tendo em mente que não temos uma variedade tão enorme de cores nos pets). Como podemos fazer?

Aguardo sugestões.

**Comment by thiagon4code** [comment]
@aluisribeiro se puder analisar isto e ver o que acha também. Podemos discutir na aula de hoje.

**Comment by aluisribeiro** [comment]
Oi @thiagon4code, realmente as únicas duas espécies aceitas no sistema é gato e cachorro. Quanto as raças, estava dando uma olhada e existem algumas tabelas já prontas. Como essa por exemplo: https://love.doghero.com.br/racas-de-cachorro. O que acha? Eu particularmente não sei se deixar aberto seria legal. Podemos ter cadastros estranhos feitos por usuários eu acredito.

**Comment by aluisribeiro** [comment]
Quanto as cores, será que não podemos deixar todas pré cadastradas com seeds também? Eu acredito que não exista uma grande variedade.

**Comment by thiagon4code** [comment]
com o que discutimos até agora sobre isso, acredito que isto #11 resolva por enquanto.

**Comment by thiagon4code** [comment]
> Oi @thiagon4code, realmente as únicas duas espécies aceitas no sistema é gato e cachorro. Quanto as raças, estava dando uma olhada e existem algumas tabelas já prontas. Como essa por exemplo: https://love.doghero.com.br/racas-de-cachorro. O que acha? Eu particularmente não sei se deixar aberto seria legal. Podemos ter cadastros estranhos feitos por usuários eu acredito.

Vou atualizar o PR  em questão com mais raças de cachorros de acordo com o site que indicou.

**Comment by thiagon4code** [comment]
Feito neste [commit](https://github.com/aluisribeiro/petsaojoao-backend/pull/11/commits/ef1a1b4cc775381410cb0c3013bbe10a7ec5403b).
